{{- if .Values.environment.cluster.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: fm-development
spec:
  encryptedData:
    .dockerconfigjson: AgCyuD+Ep9oErjk1QG4qJaRuAgd3bygUWWdl1UPs+SBiWKdkEdQa8eJJvVluO9ZHRBi0QK/KthJUua7YngfQj+USX14zs5gRStZwu5Qy74phJgHYYAeHxAPlKcwU0vXEHMT6UB1DtsiU/Ecilv2mJXi9T2ki9ghSDC2RC7m8vTV139sqTJO0SJzDnYx9Ic/HqXencLmLMmu/P7OAx6Qj5Pr2VRbvIuUsoebak9ljttx3+cL7xUA+3THCC7cp22ee/BOAIoMPcEnOioT8XxMjQ7SO3Zd87gAAiac0abH/+p27P92GHkGMSaytr+vVfe5GQURNOI0kX2CPSqR/S5ThH9D/ucYgda1kdQUgJKxgJc2XsZklDRSvQ71Mbc7qTSHqH4RS1kt3zSjvFNi4NCC0YfWXYrUB5IWehzWUDmY73pwPS1ym6fdww5h5/DmqZEHBLGv4Tlqzbyt3q+lKJQPqdUWBcrLi+FkZFbJH91RbFL4wG+6rlxWsBjSXD+UwGjcEnDUuVDS4I27PzGNv+5qg8N3ul35hjIhqKF4k/OcNnwEOIZz0pglm+noyai0h9B3smjnR0FR44p7v7MqC9x/9Jak5MNhEbE16zfhLpsoaKJDkk7LG/Mro/3ZbNwrevvaRkpnF9Kw3p1Q4IAZLWr2/d2gC1A2XPnl3Dks3ns5pbyYv9EfyLl7veMPJBxknRmuwHs543drs8ICP+sX+9jQ8tOIggFN0ugmpQU8mAWZNSxs4L0QozM+aE4hb1ISLjQYXU/3jLBmRCY9YgfwDhKj8qhUcwfwzwJM0VpLv6fD3wMelpng1NkAKrcNQ6Xc1nTatWCTATuGu19tJnIhxY4JVHueNXAZV2OKWvYzf8AfZbvnoeG5iyZV3vYzM7vave94gJ+1R52KR9wkKOegV3bU13AJbpNV4ArSH6vd0QCR7L7fi8cXcCgRroZBtmUc+dm3W7FxSL45ThA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: fm-development
    type: kubernetes.io/dockerconfigjson


{{- end }}