frinx-machine:
  frinx-machine-monitoring:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        # Values can be templated
        path: /
        pathType: Prefix
        hosts:
          - grafana.127.0.0.1.nip.io