frinx-machine:
  krakend:
    ingress:
      enabled: true
      className: nginx
      annotations:
        # force-ssl-redirect must be disabled in case you are using a self-signed certificate
        # nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      hosts:
        - host: krakend.127.0.0.1.nip.io
          paths:
            - path: "/"
              pathType: ImplementationSpecific

  workflow-manager:
    ingress:
      enabled: true
      hosts:
        - host: workflow-manager.127.0.0.1.nip.io
          paths:
            - path: "/"
              pathType: ImplementationSpecific
      schellarHosts:
        - host: workflow-manager-schellar.127.0.0.1.nip.io
          paths:
            - path: "/"
              pathType: ImplementationSpecific
